const userData =[
  {
    "id": 1,
    "name": "Shubham",
    "email": "shubham@example.com",
    "password": "123456",
    "taskCounts": {
      "active": 2,
      "newTask": 1,
      "completed": 1,
      "failed": 1
    },
    "tasks": [
      {
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false,
        "title": "Login Page",
        "description": "Build login UI",
        "date": "2026-04-02",
        "category": "Frontend"
      },
      {
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false,
        "title": "Auth Setup",
        "description": "Implement Firebase Auth",
        "date": "2026-04-03",
        "category": "Backend"
      },
      {
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false,
        "title": "Navbar",
        "description": "Responsive navbar",
        "date": "2026-04-01",
        "category": "UI"
      },
      {
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false,
        "title": "Footer",
        "description": "Design footer",
        "date": "2026-04-03",
        "category": "UI"
      },
      {
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true,
        "title": "Database Schema",
        "description": "Update schema",
        "date": "2026-04-04",
        "category": "Backend"
      }
    ]
  },
  {
    "id": 2,
    "name": "Rahul",
    "email": "rahul@example.com",
    "password": "123456",
    "taskCounts": {
      "active": 2,
      "newTask": 1,
      "completed": 1,
      "failed": 0
    },
    "tasks": [
      {
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false,
        "title": "API Integration",
        "description": "Connect frontend with backend",
        "date": "2026-04-02",
        "category": "Backend"
      },
      {
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false,
        "title": "Auth System",
        "description": "JWT login",
        "date": "2026-04-01",
        "category": "Backend"
      },
      {
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false,
        "title": "Error Handling",
        "description": "Handle API errors",
        "date": "2026-04-03",
        "category": "Backend"
      },
      {
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false,
        "title": "Filler active task",
        "description": "autogenerated to balance counts",
        "date": "2026-04-05",
        "category": "Misc"
      }
    ]
  },
  {
    "id": 3,
    "name": "Amit",
    "email": "amit@example.com",
    "password": "123456",
    "taskCounts": {
      "active": 1,
      "newTask": 1,
      "completed": 1,
      "failed": 1
    },
    "tasks": [
      {
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false,
        "title": "Database Setup",
        "description": "MongoDB schema",
        "date": "2026-03-28",
        "category": "Database"
      },
      {
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false,
        "title": "Write Queries",
        "description": "Optimize queries",
        "date": "2026-04-02",
        "category": "Database"
      },
      {
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true,
        "title": "Migration",
        "description": "Data migration",
        "date": "2026-03-29",
        "category": "Database"
      },
      {
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false,
        "title": "Filler active task",
        "description": "autogenerated to balance counts",
        "date": "2026-04-05",
        "category": "Misc"
      }
    ]
  },
  {
    "id": 4,
    "name": "Priya",
    "email": "priya@example.com",
    "password": "123456",
    "taskCounts": {
      "active": 2,
      "newTask": 1,
      "completed": 1,
      "failed": 0
    },
    "tasks": [
      {
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false,
        "title": "Dashboard UI",
        "description": "Admin dashboard",
        "date": "2026-04-03",
        "category": "UI/UX"
      },
      {
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false,
        "title": "Figma Design",
        "description": "Wireframes",
        "date": "2026-04-02",
        "category": "Design"
      },
      {
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false,
        "title": "Landing Page",
        "description": "Homepage UI",
        "date": "2026-03-30",
        "category": "UI"
      },
      {
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false,
        "title": "Filler active task",
        "description": "autogenerated to balance counts",
        "date": "2026-04-05",
        "category": "Misc"
      }
    ]
  },
  {
    "id": 5,
    "name": "Ankit",
    "email": "ankit@example.com",
    "password": "123456",
    "taskCounts": {
      "active": 2,
      "newTask": 1,
      "completed": 1,
      "failed": 0
    },
    "tasks": [
      {
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false,
        "title": "Deploy App",
        "description": "Deploy on Vercel",
        "date": "2026-04-02",
        "category": "DevOps"
      },
      {
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false,
        "title": "Server Setup",
        "description": "Node server",
        "date": "2026-03-28",
        "category": "Backend"
      },
      {
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false,
        "title": "Fix Build",
        "description": "Resolve errors",
        "date": "2026-04-03",
        "category": "DevOps"
      },
      {
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false,
        "title": "Filler active task",
        "description": "autogenerated to balance counts",
        "date": "2026-04-05",
        "category": "Misc"
      }
    ]
  }
]

const admin = [
  {
    "id": 101,
    "name": "Super Admin",
    "email": "admin@example.com",
    "password": "admin123",
    "role": "admin"
  }
]

export const setLocalStorage = ()=>{
    localStorage.setItem("employee",JSON.stringify(userData))
    localStorage.setItem("admin",JSON.stringify(admin))
}
export const getLocalStorage = ()=>{
   let employee =  JSON.parse(localStorage.getItem("employee"))
    let admin = JSON.parse(localStorage.getItem("admin"))
    return {employee, admin}
}